use_amp: false
optim: adamW
init: none
unused_parameters: true
max_epoch: 600
batch_type: folded
batch_size: 8
iterator_type: chunk
chunk_length: 300 # 4s # 8s
chunk_default_fs: 50 # GCD among all possible sampling frequencies
# chunk_max_abs_length: 100000 # max number of samples per chunk for all sampling frequencies (reduce this value if OOM occurs)
#chunk_max_abs_length: 100000
#chunk_max_abs_length: 100000
#chunk_max_abs_length: 96000
#chunk_max_abs_length: 144000
chunk_max_abs_length: 100000
num_iters_per_epoch: 8000
num_workers: 16
grad_clip: 1.0
optim_conf:
    lr: 5.0e-04
    betas: [0.8, 0.999]
    eps: 1.0e-10
    weight_decay: 1.0e-05
patience: 40
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: steplr
scheduler_conf:
    step_size: 4
    gamma: 0.99

allow_multi_rates: true

preprocessor: enh
preprocessor_conf:
    speech_volume_normalize: "0.5_1.0"
    #rir_scp: data/rir_train.scp
    rir_scp: data/rir_train_swap.scp
    rir_apply_prob: 0.5
    #noise_scp: data/noise_train.scp
    noise_scp: data/noise_train_swap.scp
    noise_apply_prob: 0.98
    noise_db_range: "-5_15"
    force_single_channel: true
    channel_reordering: true
    categories:
    - 1ch_8000Hz
    - 1ch_16000Hz
    - 1ch_22050Hz
    - 1ch_24000Hz
    - 1ch_32000Hz
    - 1ch_44100Hz
    - 1ch_48000Hz
    - 1ch_8000Hz_reverb
    - 1ch_16000Hz_reverb
    - 1ch_22050Hz_reverb
    - 1ch_24000Hz_reverb
    - 1ch_32000Hz_reverb
    - 1ch_44100Hz_reverb
    - 1ch_48000Hz_reverb
    data_aug_effects:
    - [0.5, "bandwidth_limitation", {"res_type": "random"}]
    - [0.5, "clipping", {"min_quantile": 0.1, "max_quantile": 0.9}]
    data_aug_num: [1, 1]
    data_aug_prob: 0.666666666

force_single_channel: true
channel_reordering: true
# The categories list order must be the same everywhere in this config
num_spk: 1

model_conf:
    normalize_variance_per_ch: true
    # The categories list order must be the same everywhere in this config
    categories:
    - 1ch_8000Hz
    - 1ch_16000Hz
    - 1ch_22050Hz
    - 1ch_24000Hz
    - 1ch_32000Hz
    - 1ch_44100Hz
    - 1ch_48000Hz
    - 1ch_8000Hz_reverb
    - 1ch_16000Hz_reverb
    - 1ch_22050Hz_reverb
    - 1ch_24000Hz_reverb
    - 1ch_32000Hz_reverb
    - 1ch_44100Hz_reverb
    - 1ch_48000Hz_reverb

encoder: stft
encoder_conf:
    n_fft: 256
    hop_length: 128
    use_builtin_complex: true
    default_fs: 8000
decoder: stft
decoder_conf:
    n_fft: 256
    hop_length: 128
    default_fs: 8000
separator: se_mamba
separator_conf:
    n_srcs: 1
    n_imics: 1
    mamba_blocks: 4
    mamba_layers: 1
    lstm_hidden_units: 200
    attn_n_head: 4
    attn_qk_output_channel: 2
    emb_dim: 48
    emb_ks: 4
    emb_hs: 1
    activation: prelu
    eps: 1.0e-05

# A list for criterions
# The overlall loss in the multi-task learning will be:
# loss = weight_1 * loss_1 + ... + weight_N * loss_N
# The default `weight` for each sub-loss is 1.0
criterions:
  # The first criterion
  - name: mr_l1_tfd
    conf:
      window_sz: [256, 512, 768, 1024]
      hop_sz: null
      eps: 1.0e-9
      time_domain_weight: 0.5
      normalize_variance: true
      reduction: mean
    wrapper: fixed_order
    wrapper_conf:
      weight: 1.0
  # The second criterion
  - name: si_snr
    conf:
      eps: 1.0e-7
    wrapper: fixed_order
    wrapper_conf:
      weight: 0.0